application: mil-arxiv
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /crons/checker
  script: checker.app
  login: admin

- url: /crons/sender
  script: sender.app
  login: admin

- url: /logout/logout
  script: logout.app

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
